export interface Vehicle {
  id: string;
  vehicleType: string; // Type of vehicle
  vehicleOwnerNic: string; // Name of the owner
  vehicleValue: number; // Value of the vehicle
  vehicleMonthlyIncome: number; // Monthly income generated by the vehicle
}

export interface VehicleDTO {
  vehicleType: string; // Type of vehicle
  vehicleOwnerNic: string; // Name of the owner
  vehicleValue: number; // Value of the vehicle
  vehicleMonthlyIncome: number; // Monthly income generated by the vehicle
}
