export interface FirstFormGroupDto {
  firstCtrl: string; // ගෘහ මූලික අංකය
  secondCtrl: string; // ගම
  thirdCtrl: string; // ගෘහ මූලිකයාගේ නම
  fourthCtrl: string; // ලිපිනය
  fifthCtrl: string; // දුරකථන අංකය
  sixthCtrl: string; // වට්ස්ඇප් අංකය
}
export interface PersonDto {
  name: string; // නම
  relation: string; // ගෘහ මූලිකයොට ඇති නෑකම
  dob: Date; // උපන් දිනය
  nic: string; // ජා.හැ. අංකය
  ethnicity: string; // ජාතිය
  religion: string; // ආගම
  education?: string; // අධ්‍යාපන මට්ටම/දැනට අධ්‍යාපනය ලබන ශ්‍රෙනිය
  occupation?: string; // රැකියාව/තනතුර
  income?: string; // මාසික වැටුප/ආදායම
  healthIssues?: string; // රෝගාබාධ
  remarks?: string; // ආබාධිත විස්තර
}

export interface SecondFormGroupDto {
  people: PersonDto[]; // Array of people data
}


export interface HousingInfoDTO {
  housingType: number;
  housingTypeDescription?: string;

  wallType: number; // Selected radio button value for wall type
  wallTypeDescription?: string; // Description for wall type

  floorType: number; // Selected radio button value for floor type
  floorTypeDescription?: string; // Description for floor type

  roofType: number; // Selected radio button value for roof type
  roofTypeDescription?: string; // Description for roof type

  sanitationType: number; // Selected radio button value for sanitation facilities
  sanitationTypeDescription?: string; // Description for sanitation facilities

  waterFacility: number; // Selected radio button value for water facilities
  waterFacilityDescription?: string; // Description for water facilities

  powerSource: number; // Selected radio button value for power source
  powerSourceDescription?: string; // Description for power source

  disasterRisk: number; // Selected radio button value for disaster risk
  disasterRiskDescription?: string; // Description for disaster risk
}

interface AssistanceDetails {
  institution: string; // Institution Name
  aswesomeValue?: string; // අස්වැසුම
  samrudhiValue?: string; // සමෘද්ධි
  elderlyValue?: string; // වැඩිහිටි ආධාර
  adultValue?: string; // පිළිකා ආධාර
  ignorantValue?: string; // අබොධිත
  kidneyAssistanceValue?: string; // වකුගඩු ආධාර
  publicAssistanceValue?: string; // මහජනාධාර
  medicalAssistanceValue?: string; // රෝගාධාර
  educationSupportValue?: string; // ආධ්‍යාපන ආධාර
}

interface MigrantDetailsDTO {
  name: string; // Institution Name
  country: string; // Country
  yearMigrated: string; // Year Migrated
  reasonMigrated: string; // Reason for Migration
  otherDetails?: string; // Optional Other Details
}

interface LandDetailsDTO {
  ownership: string; // Type of ownership (e.g., government, private, etc.)
  landSize: string; // Size of the land in acres
  ownerName: string; // Name of the owner
  landDetails: string; // Details of the land (name, lot number, or deed number)
  governorsArea: string; // Grama Niladhari division
  cropGrown: string; // Crops grown on the land
  monthlyIncome: string; // Monthly income from the land
}

interface VehicleDetailsDTO {
  vehicleType: string; // Type of vehicle
  vehicleOwnerName: string; // Name of the owner
  vehicleValue: string; // Value of the vehicle
  vehicleMonthlyIncome: string; // Monthly income generated by the vehicle
}

interface AssetDetailsDTO {
  assetDetails: string; // Description of the asset
  assetOwnerName: string; // Owner's name
  assetValue: string; // Value of the asset
  assetMonthlyIncome: string; // Monthly income generated from the asset
}

interface BusinessDTO {
  businessNature: string; // Nature of the business (e.g., Large Scale, Medium Scale, Self-Employment, etc.)
  businessName: string; // Business name or department
  employeeCount: string; // Number of employees
  businessAddress: string; // Address of the business
  monthlyIncome: string; // Monthly income from the business
  businessOtherDetails: string; // Other business details (optional)
}

interface OtherActivitiesDTO {
  ownerName: string; // Owner's name
  activityAddress: string; // Address of the activity
  monthlyIncome: string; // Monthly income from the activity
  additionalDetails: string; // Other additional details (optional)
}

interface SpecialNotesDTO {
  specialNotes: string; // The special notes entered by the user
}


export interface CombinedFormDto {
  householdInfo: FirstFormGroupDto;
  people?: PersonDto[];
  housingInfo?: HousingInfoDTO;
  assistanceDetails?: AssistanceDetails[];
  migrantDetails?: MigrantDetailsDTO[];
  landDetails?: LandDetailsDTO[];
  vehicleDetails?: VehicleDetailsDTO[];
  assetDetails?: AssetDetailsDTO[];
  businessDetails?: BusinessDTO[];
  otherActivities?: OtherActivitiesDTO[];
  specialNotes?: SpecialNotesDTO;
}
